# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: 'Kani Rust Verifier'
description: 'Run the Kani Rust Verifier on a Rust Crate'
author: 'Kani Contributors'

branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  command:
    description: 'Command to run.'
    required: false
    default: 'cargo-kani'

runs:
  using: "composite"
  steps:
    - name: Install Kani
      shell: bash
      run: |
        export KANI_VERSION="0.11.0"; \
        export KANI_SCRIPT_FOLDER="https://raw.githubusercontent.com/model-checking/kani/kani-${KANI_VERSION}/scripts/setup"; \
        curl "${KANI_SCRIPT_FOLDER}/ubuntu/install_deps.sh" | bash ; \
        curl "${KANI_SCRIPT_FOLDER}/install_rustup.sh" | bash  ; \
        source  ~/.cargo/env; \
        cargo install --version $KANI_VERSION --locked kani-verifier; \
        cargo-kani setup;

    - name: Run Kani
      shell: bash
      run: | 
        source  ~/.cargo/env; \
        ${{ inputs.command }}

