# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT


- name: Kani Rust Verifier
  uses: model-checking/kani-github-action@v0.13-alpha
  with:
    command: cd tests/cargo-kani/simple-lib && cargo-kani
