# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Kani Action Check
on: pull_request

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Ensure that the Kani action continues to work
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Kani
        uses: model-checking/kani-github-action@v0.13-alpha
        with:
          working-directory: tests/cargo-kani/simple-lib
